<?php

namespace AppBundle\Repository;

/**
 * followRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class followRepository extends \Doctrine\ORM\EntityRepository
{
}
